name: roll
on:
  schedule:
    - cron:  '0 14 * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: SetUp Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9.4
        architecture: x64
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 install httpx lxml
        
    - name: Checkout Resource
      uses: actions/checkout@v2
      
    - name: roll
      run: |
        python3 ./roll.py > result
      shell: bash
      
    - name: Commit changes
      uses: EndBug/add-and-commit@v7
      with:
        author_name: github-actions
        author_email: 41898282+github-actions[bot]@users.noreply.github.com
        message: 'roll by git action'
        add: '.'
